dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.14.1
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.4.1
